import React from 'react'
import styles from './Blogs.module.css'
import BlogCard from '../../assets/components/BlogCard/BlogCard'
import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../../assets/components/NavBar/NavBar'
import { NextFetchEvent } from 'next/server'
import { motion } from 'framer-motion'
import { useRef } from "react";
import { useInView } from "framer-motion";

const Blogs = ({ blogposts }) => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });
  return (
    <>
    <div className={styles.main} >
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>B L O G S</h1>
      
        {/* <h1 className={styles.blogtitle}>{blogposts[0]["title"]}</h1> */}
        {/* <BlogCard data={blogposts[5]}/> */}
        { blogposts.reverse().map((blogpost, i) => {
          // console.log(blogpost)
          if(blogpost.picture){
            return <motion.div
            initial = {{opacity: 0, y: 200}}
            whileInView = {{opacity: 1, y: 0}}
            transition = {{duration: 0.5, ease: 'easeOut', type: 'tween'}}
            viewport = {{once: true}}
            className={styles.blogWrapper}>
              <BlogCard data={blogpost}/>
              </motion.div>
          }
        }) }
      
    {/* <div className={styles.parent}>
      <div className={styles.child}></div>
    </div> */}
 </div>
    </>
  )
}

export default Blogs

export async function getServerSideProps() {
  const response = await fetch("https://blog-eight-nu-79.vercel.app/api/blogposts")
  const data = await response.json()
  return {
    props: {
      blogposts: data["data"],
    },
  }
}